x = int(input("please give your first number for demostration :"))
y = int(input("please give your second number for demostration :"))
print('\n\nThe following are the arithematic operators :')
print("this is your sum operater and it is denoted by \"+\" and the sum is :", x+y)
print("this is your subraction operater and it is denoted by \"-\" and the subraction results are :", x-y)
print("this is your multiplication operater and it is denoted by \"*\" and the results of multiplication are :", x*y)
print("this is your division operater and it is denoted by \"/\" and the results of division are :", x/y)
print("\n\nThe following are the logical operators")
print("this is your greater than relational operator and it is denoted by \"<\". This prints true or false because this relates with two things ;", x>y)
print("this is your less than relational operator and it is denoted by \"<\". This prints true or false because this relates with two things ;", x<y)
print("this is your comparing relational operator and it is denoted by \"<\". This prints true or false because this relates with two things ;", x==y)
print("this is your not equal to relational operator and it is denoted by \"<\". This prints true or false because this relates with two things ;", x!= y)
print("this is your less than or equal to relational operator and it is denoted by \"<\". This prints true or false because this relates with two things ;", x<=y)
print("this is your greater than or equal to relational operator and it is denoted by \"<\". This prints true or false because this relates with two things ;", x>=y)
